services:
  - type: web
    name: pynote
    runtime: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: USE_DOCKER
        value: "false"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
